[project]
name = "cv-forge-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "alembic==1.16.5",
  "asyncpg==0.30.0",
  "fastapi==0.116.1",
  "httpx==0.28.1",
  "pgvector==0.4.1",
  "pydantic-settings==2.10.1",
  "pyjwt[crypto]==2.10.1",
  "redis==6.4.0",
  "sqlalchemy[asyncio]==2.0.43",
  "svix==1.75.0",
  "uvicorn[standard]==0.35.0",
]

[project.scripts]
app = "app.cli:main"

[dependency-groups]
dev = [
  "aiosqlite==0.21.0",
  "black==25.1.0",
  "pytest==8.4.1",
  "pytest-asyncio==1.1.0",
  "pytest-cov==6.2.1",
  "ruff==0.12.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.black]
line-length = 100
target-version = ["py311"]
