import { ArrowRight, CircleCheck, FileText, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { skillBank, versions } from '../lib/demo'
export function Dashboard(){const bullets=skillBank.reduce((n,i)=>n+i.bullets.length,0);return <div className="page-enter px-5 py-8 md:px-10 md:py-12 xl:px-16 xl:py-14">
  <header className="mb-14 grid gap-8 border-b pb-10 xl:grid-cols-[1.4fr_.6fr] xl:items-end"><div><p className="eyebrow mb-5">Thursday, 30 July</p><h1 className="display max-w-4xl">Your career evidence,<br/><em className="font-normal text-accent">ready to shape.</em></h1></div><p className="max-w-md text-muted xl:justify-self-end">Maintain one trusted source of experience. ResumeForge selects the right evidence for each role—nothing is applied without your approval.</p></header>
  <section aria-labelledby="bank-summary" className="mb-16 grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><div><div className="mb-6 flex items-end justify-between"><div><p className="eyebrow mb-2">Source of truth</p><h2 id="bank-summary" className="section-title">Skill bank</h2></div><Link className="button-ghost" to="/skill-bank">Open bank <ArrowRight size={16}/></Link></div><div className="divide-y border-y">{skillBank.map(item=><div key={item.id} className="grid gap-3 py-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-muted">{item.organization} · {item.bullets.length} evidence {item.bullets.length===1?'point':'points'}</p></div><div className="flex flex-wrap gap-1.5">{item.skills.slice(0,3).map(s=><span className="tag" key={s.id}>{s.name}</span>)}</div></div>)}</div></div>
  <aside className="bg-ink p-7 text-canvas dark:bg-raised dark:text-ink"><p className="eyebrow !text-canvas/60 dark:!text-muted">Bank health</p><p className="mt-8 font-display text-6xl">{bullets}<span className="ml-2 text-2xl italic opacity-60">proof points</span></p><div className="mt-8 space-y-3 border-t border-canvas/20 pt-5 text-sm"><p className="flex items-center gap-2"><CircleCheck size={16} className="text-success"/>All bullets carry skill tags</p><p className="flex items-center gap-2"><CircleCheck size={16} className="text-success"/>3 entries updated this month</p></div><Link to="/skill-bank" className="button mt-8 w-full bg-canvas text-ink dark:bg-ink dark:text-canvas"><Plus size={16}/>Add evidence</Link></aside></section>
  <section aria-labelledby="recent"><div className="mb-6 flex items-end justify-between"><div><p className="eyebrow mb-2">Working drafts</p><h2 id="recent" className="section-title">Recent versions</h2></div><Link className="button-ghost" to="/editor">Open editor <ArrowRight size={16}/></Link></div><div className="overflow-x-auto border-y"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-muted"><tr><th className="py-3 font-semibold">Version</th><th className="py-3 font-semibold">Updated</th><th className="py-3 font-semibold">ATS coverage</th><th className="py-3 text-right font-semibold">State</th></tr></thead><tbody className="divide-y">{versions.map(v=><tr key={v.id}><td className="py-5"><Link className="flex items-center gap-3 font-semibold hover:text-accent" to="/editor"><FileText size={17}/>{v.name}</Link></td><td className="py-5 text-muted">{v.updatedAt}</td><td className="py-5 font-mono text-xs">{v.atsScore}%</td><td className="py-5 text-right"><span className="tag">Draft</span></td></tr>)}</tbody></table></div></section>
  </div>}
