import Editor from '@monaco-editor/react'
import { AlertTriangle, Check, ChevronDown, Download, History, Play, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { AsyncProgress } from '../components/AsyncProgress'
import { tex, versions } from '../lib/demo'
import { useUI } from '../store/ui'
import type { JobState } from '../lib/types'
export function LatexEditor(){const {theme}=useUI();const [source,setSource]=useState(tex);const [state,setState]=useState<JobState>('done');const [progress,setProgress]=useState(100);const [mobilePane,setMobilePane]=useState<'source'|'preview'>('source');const [history,setHistory]=useState(false);const hasError=source.includes('\\badcommand');const compile=()=>{setState('running');setProgress(14);const timer=setInterval(()=>setProgress(p=>Math.min(p+24,94)),380);setTimeout(()=>{clearInterval(timer);setState(hasError?'failed':'done');setProgress(100);if(!hasError)setMobilePane('preview')},1700)};useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();compile()}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)});return <div className="flex min-h-screen flex-col bg-surface">
  <header className="no-print flex min-h-16 flex-wrap items-center justify-between gap-3 border-b bg-canvas px-4 py-2 md:px-6"><div className="flex min-w-0 items-center gap-3"><div><p className="eyebrow">Resume version</p><button className="flex items-center gap-1 truncate font-semibold">Fathom · Senior Product Engineer <ChevronDown size={15}/></button></div></div><div className="flex items-center gap-1"><span className={`mr-2 hidden items-center gap-2 text-xs font-semibold sm:flex ${state==='failed'?'text-danger':state==='done'?'text-success':'text-warning'}`}>{state==='done'?<Check size={15}/>:state==='failed'?<AlertTriangle size={15}/>:<span className="status-dot animate-pulse"/>}{state==='done'?'Compiled':state==='failed'?'Compile failed':'Compiling'}</span><button className="button-ghost" onClick={()=>setHistory(!history)}><History size={16}/><span className="hidden sm:inline">History</span></button><button className="button-secondary"><Save size={16}/><span className="hidden sm:inline">Save</span></button><button className="button-primary" onClick={compile} disabled={state==='running'}><Play size={16}/>Compile</button></div></header>
  {state==='running'&&<AsyncProgress state={state} progress={progress} stage={progress<45?'Validating LaTeX source':progress<80?'Tectonic is typesetting':'Preparing preview'}/>} {state==='failed'&&<div role="alert" className="flex items-center gap-3 border-b bg-danger/10 px-5 py-3 text-sm text-danger"><AlertTriangle size={17}/><span><strong>Compilation stopped on line 8.</strong> Undefined control sequence <code className="font-mono">\\badcommand</code>.</span></div>}
  <div className="no-print flex border-b lg:hidden" role="tablist"><button className={`min-h-11 flex-1 border-b-2 text-sm font-semibold ${mobilePane==='source'?'border-accent':'border-transparent text-muted'}`} onClick={()=>setMobilePane('source')}>LaTeX source</button><button className={`min-h-11 flex-1 border-b-2 text-sm font-semibold ${mobilePane==='preview'?'border-accent':'border-transparent text-muted'}`} onClick={()=>setMobilePane('preview')}>PDF preview</button></div>
  <div className="relative grid min-h-0 flex-1 lg:grid-cols-2"><section aria-label="LaTeX source editor" className={`${mobilePane==='source'?'block':'hidden'} min-h-[70vh] border-r lg:block`}><Editor height="100%" defaultLanguage="latex" value={source} onChange={v=>setSource(v??'')} theme={theme==='dark'?'vs-dark':'vs'} options={{minimap:{enabled:false},fontFamily:'IBM Plex Mono',fontSize:13,lineHeight:22,wordWrap:'on',padding:{top:20,bottom:20},scrollBeyondLastLine:false,automaticLayout:true,renderLineHighlight:'line'}}/></section><section aria-label="PDF preview" className={`${mobilePane==='preview'?'flex':'hidden'} min-h-[70vh] items-start justify-center overflow-auto bg-[oklch(91%_.012_70)] p-4 dark:bg-[oklch(15%_.01_60)] md:p-8 lg:flex`}><ResumePreview/></section>
  {history&&<aside className="absolute inset-y-0 right-0 z-20 w-full max-w-sm border-l bg-canvas p-5 shadow-quiet"><div className="mb-8 flex items-center justify-between"><h2 className="section-title">Version history</h2><button className="button-ghost" onClick={()=>setHistory(false)}>Close</button></div><ol className="space-y-1">{versions.map((v,i)=><li key={v.id}><button className="w-full border-b py-4 text-left"><span className="flex items-center justify-between gap-4"><strong className="text-sm">{i===0?'Current draft':`Version ${versions.length-i}`}</strong><span className="font-mono text-xs text-muted">{v.updatedAt}</span></span><span className="mt-1 block text-xs text-muted">ATS coverage {v.atsScore}%</span></button></li>)}</ol></aside>}</div>
  </div>}
function ResumePreview(){return <div className="min-h-[54rem] w-full max-w-[42rem] bg-[oklch(99%_.005_80)] p-[clamp(2rem,7vw,4.5rem)] text-[oklch(19%_.01_50)] shadow-quiet"><header className="border-b border-black/30 pb-4 text-center"><h2 className="font-serif text-2xl font-bold">Dhruv Sharma</h2><p className="mt-1 font-serif text-[11px]">Bengaluru, India · dhruv@example.com · github.com/dhruv</p></header><PreviewSection title="Experience"><p className="font-serif text-sm font-bold">Product Engineer <span className="float-right font-normal">2023—Present</span></p><p className="font-serif text-xs italic">Northstar Labs, Bengaluru</p><ul className="mt-2 list-disc space-y-1 pl-4 font-serif text-[11px] leading-[1.45]"><li>Owned a cross-functional React and TypeScript release workflow, reducing median deployment setup from 18 minutes to 6 minutes.</li><li>Architected a PostgreSQL audit-log pipeline processing 2.4M monthly events with traceable retention controls.</li></ul></PreviewSection><PreviewSection title="Projects"><p className="font-serif text-sm font-bold">Papertrail <span className="font-normal">— React, FastAPI, Python</span></p><ul className="mt-2 list-disc pl-4 font-serif text-[11px] leading-[1.45]"><li>Built a local-first document index with conflict-safe sync and full-text search across 12,000 notes.</li></ul></PreviewSection><div className="no-print mt-16 flex justify-center"><button className="button-secondary text-ink"><Download size={15}/>Download PDF</button></div></div>}
function PreviewSection({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-5"><h3 className="mb-2 border-b border-black/60 pb-1 font-serif text-sm font-bold uppercase tracking-wider">{title}</h3>{children}</section>}
