import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, ArrowRight, Check, FileUp, LoaderCircle, RotateCw, Sparkles } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { ScreenState } from '../components/ScreenState'
import { useApi } from '../hooks/useApi'
import { useBackgroundJobStatus } from '../hooks/useBackgroundJobStatus'
import { ApiError } from '../lib/api'
import type { JobDescription, JDParseQueued } from '../lib/types'

const date=new Intl.DateTimeFormat(undefined,{dateStyle:'medium'})

export function JDInput(){
  const api=useApi(),queryClient=useQueryClient(),[params,setParams]=useSearchParams(),[mode,setMode]=useState<'paste'|'upload'>('paste'),[text,setText]=useState(''),[file,setFile]=useState<File|null>(null),[queued,setQueued]=useState<JDParseQueued|null>(null)
  const settings=useQuery({queryKey:['llm-settings'],queryFn:api.llmSettings.get,retry:(count,error)=>error instanceof ApiError&&error.status===404?false:count<1})
  const jds=useQuery({queryKey:['jds'],queryFn:api.jd.list,enabled:!!settings.data})
  const submit=useMutation({mutationFn:()=>mode==='paste'?api.jd.parseText(text.trim()):api.jd.parsePdf(file!),onSuccess:async result=>{setQueued(result);setParams({jd:result.job_description_id});await queryClient.invalidateQueries({queryKey:['jds']})}})
  const job=useBackgroundJobStatus(queued?.background_job_id)
  const selectedId=queued?.job_description_id??params.get('jd')
  const detail=useQuery({queryKey:['jd',selectedId],queryFn:()=>api.jd.get(selectedId!),enabled:!!selectedId&&(!queued||job.data?.status==='done')})
  useEffect(()=>{if(job.data?.status==='done'||job.data?.status==='failed')void queryClient.invalidateQueries({queryKey:['jds']})},[job.data?.status,queryClient])
  if(settings.isPending)return <div className="px-5 py-8 md:px-10 xl:px-16"><ScreenState kind="loading" title="Checking AI readiness…" detail="Looking for your saved provider."/></div>
  if(settings.error instanceof ApiError&&settings.error.status===404)return <div className="page-enter px-5 py-8 md:px-10 md:py-12 xl:px-16"><PageHeader eyebrow="Target role" title="Job Descriptions"/><div className="border-l-4 border-accent bg-surface px-6 py-9"><p className="eyebrow">Provider Required</p><h2 className="mt-3 section-title">Add an LLM provider before parsing a job description.</h2><p className="mt-2 max-w-xl text-sm text-muted">Save your provider, model, and API key once. ResumeForge uses that configuration for your parsing jobs.</p><Link className="button-primary mt-6" to="/settings">Open LLM Settings</Link></div></div>
  if(settings.isError)return <div className="px-5 py-8 md:px-10 xl:px-16"><ScreenState kind="error" title="AI settings unavailable" detail={settings.error.message} onRetry={()=>void settings.refetch()}/></div>
  const terminalError=job.data?.status==='failed'?job.data.error:null
  return <div className="page-enter px-5 py-8 md:px-10 md:py-12 xl:px-16"><PageHeader eyebrow="Target role" title="Job Descriptions" description="Provide the source. ResumeForge separates requirements from preferences before it touches your resume."/>
    <div className="grid gap-12 xl:grid-cols-[minmax(0,1.05fr)_minmax(22rem,.95fr)]"><section aria-labelledby="jd-source"><h2 id="jd-source" className="sr-only">Job description source</h2><div role="tablist" aria-label="Job description input" className="mb-5 flex border-b"><button role="tab" aria-selected={mode==='paste'} onClick={()=>setMode('paste')} className={`min-h-11 border-b-2 px-4 text-sm font-semibold ${mode==='paste'?'border-accent':'border-transparent text-muted'}`}>Paste Text</button><button role="tab" aria-selected={mode==='upload'} onClick={()=>setMode('upload')} className={`min-h-11 border-b-2 px-4 text-sm font-semibold ${mode==='upload'?'border-accent':'border-transparent text-muted'}`}>Upload PDF</button></div>{mode==='paste'?<label className="block text-sm font-semibold" htmlFor="jd-text">Job Description<textarea id="jd-text" name="job-description" className="field mt-2 min-h-[24rem] resize-y py-3 leading-6" autoComplete="off" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste the complete job description here…"/></label>:<label className="grid min-h-[24rem] cursor-pointer place-items-center border border-dashed bg-surface text-center hover:bg-raised" htmlFor="jd-file"><input id="jd-file" name="job-description-pdf" type="file" accept="application/pdf,.pdf" className="sr-only" onChange={event=>setFile(event.target.files?.[0]??null)}/><span><FileUp className="mx-auto mb-4 text-muted" aria-hidden="true"/><span className="block font-semibold">{file?file.name:'Choose a job description PDF'}</span><span className="mt-1 block text-sm text-muted">PDF up to 10&nbsp;MB</span></span></label>}<div className="mt-5 flex flex-wrap items-center justify-between gap-4"><p className="text-xs text-muted">Parsing runs in the background; you can keep this page open.</p><button disabled={submit.isPending||(mode==='paste'?!text.trim():!file)} className="button-primary" onClick={()=>submit.mutate()}><Sparkles size={16} aria-hidden="true"/>{submit.isPending?'Queuing…':'Parse Requirements'}</button></div>{submit.error&&<p className="mt-4 text-sm text-danger" role="alert">{submit.error.message}</p>}</section>
      <section aria-labelledby="parsed"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow mb-2">Structured read</p><h2 id="parsed" className="section-title">Parsed Requirements</h2></div>{detail.data?.status==='done'&&<span className="flex items-center gap-2 text-sm font-semibold text-success"><Check size={16} aria-hidden="true"/>Ready</span>}</div>{queued&&(job.isPending||job.data?.status==='queued'||job.data?.status==='running')?<ParsingStatus status={job.data?.status??'queued'}/>:terminalError?<Failed error={terminalError} onRetry={()=>submit.mutate()}/>:detail.isPending&&selectedId?<div className="h-48 animate-pulse border-y bg-surface"/>:detail.isError?<ScreenState kind="error" title="Result unavailable" detail={detail.error.message} onRetry={()=>void detail.refetch()}/>:detail.data?.parsed_json?<ParsedResult detail={detail.data}/>:<div className="grid min-h-64 place-items-center border-y text-center text-sm text-muted">Submit a job description or open a previous result.</div>}</section></div>
    <section className="mt-16" aria-labelledby="history"><h2 id="history" className="section-title">Previous Job Descriptions</h2>{jds.isPending?<div className="mt-5 h-32 animate-pulse bg-surface"/>:jds.isError?<div className="mt-5"><ScreenState kind="error" title="History unavailable" detail={jds.error.message} onRetry={()=>void jds.refetch()}/></div>:<div className="mt-5 divide-y border-y">{jds.data.map(item=><Link key={item.id} className="grid gap-2 py-5 hover:text-accent sm:grid-cols-[1fr_auto] sm:items-center" to={`/job-description?jd=${item.id}`} onClick={()=>setQueued(null)}><div className="min-w-0"><p className="truncate font-semibold">{item.excerpt||'PDF job description'}</p><time className="mt-1 block font-mono text-xs text-muted" dateTime={item.created_at}>{date.format(new Date(item.created_at))}</time></div><span className="tag w-fit capitalize">{item.status}</span></Link>)}{!jds.data.length?<p className="py-7 text-sm text-muted">No job descriptions yet.</p>:null}</div>}</section>
  </div>
}

function ParsingStatus({status}:{status:string}){return <div className="border-y bg-surface px-5 py-8" role="status" aria-live="polite"><LoaderCircle className="mb-4 animate-spin text-accent" aria-hidden="true"/><p className="font-semibold">{status==='queued'?'Waiting for the worker…':'Parsing requirements…'}</p><p className="mt-2 text-sm text-muted">PDF extraction and provider calls happen outside this request.</p></div>}
function Failed({error,onRetry}:{error:string;onRetry:()=>void}){const provider=/key|provider|settings|rate limit/i.test(error);return <div className="border-y px-5 py-8" role="alert"><AlertTriangle className="mb-4 text-danger" aria-hidden="true"/><p className="font-semibold">Parsing failed</p><p className="mt-2 text-sm text-muted">{error}</p><div className="mt-5 flex flex-wrap items-center gap-3"><button className="button-secondary" onClick={onRetry}><RotateCw size={16} aria-hidden="true"/>Retry Parse</button>{provider&&<Link className="text-sm font-semibold text-accent underline underline-offset-4" to="/settings">Check LLM Settings</Link>}</div></div>}
function ParsedResult({detail}:{detail:JobDescription}){const parsed=detail.parsed_json!,verbs=parsed.action_verbs??detail.action_verbs??[];return <div><div className="divide-y border-y"><Requirement title="Required Skills" items={parsed.required_skills}/><Requirement title="Nice to Have" items={parsed.nice_to_have_skills}/><div className="py-6"><p className="eyebrow mb-3">Seniority</p><span className="tag capitalize">{parsed.seniority}</span></div><Requirement title="ATS Keywords" items={parsed.ats_keywords}/>{verbs.length?<Requirement title="Action verbs to echo" items={verbs}/>:null}<div className="py-6"><p className="eyebrow mb-3">Responsibilities</p>{parsed.responsibilities.length?<ul className="space-y-2">{parsed.responsibilities.map(item=><li key={item} className="flex gap-3 text-sm"><span className="mt-2 size-1 shrink-0 rounded-full bg-accent" aria-hidden="true"/>{item}</li>)}</ul>:<p className="text-sm text-muted">None identified.</p>}</div></div><Link className="button-primary mt-6" to={`/review?jd=${detail.id}`}>Match my resume to this job<ArrowRight size={16} aria-hidden="true"/></Link></div>}
function Requirement({title,items}:{title:string;items:string[]}){return <div className="py-6"><p className="eyebrow mb-3">{title}</p>{items.length?<div className="flex flex-wrap gap-2">{items.map(item=><span className="tag break-all" key={item}>{item}</span>)}</div>:<p className="text-sm text-muted">None identified.</p>}</div>}
