import { Check, FileUp, Sparkles } from 'lucide-react'
import { useRef, useState } from 'react'
import { AsyncProgress } from '../components/AsyncProgress'
import { PageHeader } from '../components/PageHeader'
import { jd } from '../lib/demo'
import type { JobState } from '../lib/types'
export function JDInput(){const [mode,setMode]=useState<'paste'|'upload'>('paste');const [text,setText]=useState('');const [state,setState]=useState<JobState>('done');const [progress,setProgress]=useState(100);const [parsed,setParsed]=useState(true);const timer=useRef<number>();const process=()=>{setState('running');setProgress(12);setParsed(false);let p=12;timer.current=window.setInterval(()=>{p+=22;setProgress(Math.min(p,96));if(p>=96){clearInterval(timer.current);setTimeout(()=>{setState('done');setProgress(100);setParsed(true)},500)}},450)};return <div className="page-enter px-5 py-8 md:px-10 md:py-12 xl:px-16"><PageHeader eyebrow="Target role" title="Job description" description="Provide the source. ResumeForge separates requirements from preferences before it touches your resume."/>
  <div className="grid gap-12 xl:grid-cols-[minmax(0,1.05fr)_minmax(22rem,.95fr)]"><section><div role="tablist" className="mb-5 flex border-b"><button role="tab" aria-selected={mode==='paste'} onClick={()=>setMode('paste')} className={`min-h-11 border-b-2 px-4 text-sm font-semibold ${mode==='paste'?'border-accent':'border-transparent text-muted'}`}>Paste text</button><button role="tab" aria-selected={mode==='upload'} onClick={()=>setMode('upload')} className={`min-h-11 border-b-2 px-4 text-sm font-semibold ${mode==='upload'?'border-accent':'border-transparent text-muted'}`}>Upload PDF</button></div>{mode==='paste'?<label className="block text-sm font-semibold">Job description<textarea className="field mt-2 min-h-[24rem] resize-y py-3 leading-6" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste the complete job description here…"/></label>:<label className="grid min-h-[24rem] cursor-pointer place-items-center border border-dashed bg-surface text-center hover:bg-raised"><input type="file" accept="application/pdf" className="sr-only" onChange={()=>process()}/><span><FileUp className="mx-auto mb-4 text-muted"/><span className="block font-semibold">Choose a job description PDF</span><span className="mt-1 block text-sm text-muted">PDF up to 10 MB</span></span></label>}<div className="mt-5 flex items-center justify-between gap-4"><p className="text-xs text-muted">Your source text stays attached to this target role.</p><button disabled={state==='running'||(mode==='paste'&&!text.trim())} className="button-primary" onClick={process}><Sparkles size={16}/>Parse requirements</button></div></section>
  <section aria-labelledby="parsed"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow mb-2">Structured read</p><h2 id="parsed" className="section-title">Parsed requirements</h2></div>{parsed&&<span className="flex items-center gap-2 text-sm font-semibold text-success"><Check size={16}/>Reviewed</span>}</div>{!parsed?<AsyncProgress state={state} progress={progress} stage={progress<40?'Reading source document':progress<75?'Separating requirements':'Extracting ATS language'}/>:<div className="divide-y border-y"><Requirement title="Required" items={jd.requiredSkills}/><Requirement title="Nice to have" items={jd.niceToHaveSkills}/><Requirement title="ATS language" items={jd.atsKeywords}/><div className="py-6"><p className="eyebrow mb-3">Responsibilities</p><ul className="space-y-2">{jd.responsibilities.map(x=><li key={x} className="flex gap-3 text-sm"><span className="mt-2 size-1 shrink-0 rounded-full bg-accent"/>{x}</li>)}</ul></div></div>}</section></div>
  </div>}
function Requirement({title,items}:{title:string;items:string[]}){return <div className="py-6"><p className="eyebrow mb-3">{title}</p><div className="flex flex-wrap gap-2">{items.map(x=><span className="tag" key={x}>{x}</span>)}</div></div>}
