import { ArrowRight, Check, RotateCcw, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { suggestions as seed } from '../lib/demo'
import type { RewriteSuggestion } from '../lib/types'
export function MatchReview(){const [items,setItems]=useState(seed);const counts=useMemo(()=>({approved:items.filter(i=>i.decision==='approved').length,rejected:items.filter(i=>i.decision==='rejected').length,pending:items.filter(i=>i.decision==='pending').length}),[items]);const decide=(id:string,decision:RewriteSuggestion['decision'])=>setItems(x=>x.map(i=>i.id===id?{...i,decision}:i));return <div className="page-enter px-5 py-8 md:px-10 md:py-12 xl:px-16"><PageHeader eyebrow="Fathom · Senior Product Engineer" title="Match & review" description="Every rewrite is a proposal. Compare it with your source evidence before deciding." action={<Link to="/editor" className={`button-primary ${counts.pending?'pointer-events-none opacity-45':''}`}>Assemble resume <ArrowRight size={16}/></Link>}/>
  <div className="sticky top-16 z-20 mb-8 flex flex-wrap items-center justify-between gap-4 border-y bg-canvas/95 py-3 backdrop-blur lg:top-0"><p className="text-sm"><strong>{counts.pending}</strong> decisions remaining</p><div className="flex gap-4 text-xs font-semibold"><span className="text-success">{counts.approved} approved</span><span className="text-danger">{counts.rejected} rejected</span></div></div>
  <div className="space-y-8">{items.map((item,index)=><article key={item.id} className={`border-y transition-colors ${item.decision==='approved'?'border-success/40 bg-success/5':item.decision==='rejected'?'border-danger/40 opacity-60':''}`}><header className="flex flex-wrap items-center justify-between gap-4 px-1 py-4"><div><p className="eyebrow">{item.section} · Selection {String(index+1).padStart(2,'0')}</p><p className="mt-1 text-sm font-semibold">{item.relevance}% relevance</p></div><div className="flex flex-wrap gap-1.5">{item.matchedKeywords.map(x=><span className="tag" key={x}>{x}</span>)}</div></header><div className="grid border-y lg:grid-cols-2"><div className="p-5 lg:border-r"><p className="eyebrow mb-3">Original evidence</p><p className="leading-7 text-muted">{item.sourceBullet.text}</p></div><div className="bg-surface p-5"><p className="eyebrow mb-3">Tailored proposal</p><Diff original={item.sourceBullet.text} tailored={item.tailoredText}/></div></div><footer className="flex items-center justify-between gap-4 px-1 py-4"><p className={`text-sm font-semibold ${item.decision==='approved'?'text-success':item.decision==='rejected'?'text-danger':'text-muted'}`}>{item.decision==='pending'?'Awaiting your decision':item.decision==='approved'?'Approved for this version':'Excluded from this version'}</p><div className="flex gap-2">{item.decision!=='pending'&&<button className="button-ghost" onClick={()=>decide(item.id,'pending')}><RotateCcw size={15}/>Reset</button>}<button aria-pressed={item.decision==='rejected'} className="button-secondary text-danger" onClick={()=>decide(item.id,'rejected')}><X size={16}/>Reject</button><button aria-pressed={item.decision==='approved'} className="button-primary" onClick={()=>decide(item.id,'approved')}><Check size={16}/>Approve</button></div></footer></article>)}</div>
  </div>}
function Diff({original,tailored}:{original:string;tailored:string}){const oldWords=new Set(original.toLowerCase().replace(/[,.]/g,'').split(' '));return <p className="leading-7">{tailored.split(' ').map((word,i)=><span key={`${word}-${i}`} className={!oldWords.has(word.toLowerCase().replace(/[,.]/g,''))?'bg-accent-soft text-accent decoration-clone':''}>{word} </span>)}</p>}
