import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, KeyRound, Save, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { ScreenState } from '../components/ScreenState'
import { useApi } from '../hooks/useApi'
import { ApiError } from '../lib/api'
import type { LLMSettings, SupportedModels } from '../lib/types'

export function Settings(){
  const api=useApi(),queryClient=useQueryClient(),[editing,setEditing]=useState(false),[testResult,setTestResult]=useState<{success:boolean;error:string|null}|null>(null),[confirmRemove,setConfirmRemove]=useState(false)
  const supported=useQuery({queryKey:['supported-models'],queryFn:api.llmSettings.supportedModels})
  const current=useQuery({queryKey:['llm-settings'],queryFn:api.llmSettings.get,retry:(count,error)=>error instanceof ApiError&&error.status===404?false:count<1})
  const notConfigured=current.error instanceof ApiError&&current.error.status===404
  const save=useMutation({mutationFn:api.llmSettings.save,onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:['llm-settings']});setEditing(false);setTestResult(null)}})
  const remove=useMutation({mutationFn:api.llmSettings.remove,onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:['llm-settings']});setConfirmRemove(false);setEditing(false);setTestResult(null)}})
  const test=useMutation({mutationFn:api.llmSettings.test,onSuccess:setTestResult,onError:error=>setTestResult({success:false,error:error.message})})
  if(supported.isPending||current.isPending)return <div className="px-5 py-8 md:px-10 xl:px-16"><ScreenState kind="loading" title="Loading provider settings…" detail="Checking your saved configuration."/></div>
  if(supported.isError||(!notConfigured&&current.isError))return <div className="px-5 py-8 md:px-10 xl:px-16"><ScreenState kind="error" title="Settings unavailable" detail={(supported.error??current.error)?.message??'Try loading settings again.'} onRetry={()=>{void supported.refetch();void current.refetch()}}/></div>
  const configured=current.data
  return <div className="page-enter px-5 py-8 md:px-10 md:py-12 xl:px-16"><PageHeader eyebrow="Bring your own key" title="LLM Settings" description="ResumeForge has no shared AI budget. Your provider bills only your usage, and your saved key is never shown again."/>
    {configured&&!editing?<SavedSettings settings={configured} testPending={test.isPending} testResult={testResult} onTest={()=>test.mutate()} onEdit={()=>setEditing(true)} confirmRemove={confirmRemove} onConfirmRemove={()=>setConfirmRemove(true)} onCancelRemove={()=>setConfirmRemove(false)} onRemove={()=>remove.mutate()} removePending={remove.isPending}/>:<SettingsForm supported={supported.data} current={configured} pending={save.isPending} error={save.error?.message} onCancel={configured?()=>setEditing(false):undefined} onSave={values=>save.mutate(values)}/>} 
  </div>
}

function SavedSettings({settings,testPending,testResult,onTest,onEdit,confirmRemove,onConfirmRemove,onCancelRemove,onRemove,removePending}:{settings:LLMSettings;testPending:boolean;testResult:{success:boolean;error:string|null}|null;onTest:()=>void;onEdit:()=>void;confirmRemove:boolean;onConfirmRemove:()=>void;onCancelRemove:()=>void;onRemove:()=>void;removePending:boolean}){return <section className="max-w-3xl border-y py-7"><div className="grid gap-6 sm:grid-cols-3"><div><p className="eyebrow">Provider</p><p className="mt-2 font-semibold capitalize">{settings.provider}</p></div><div><p className="eyebrow">Model</p><p className="mt-2 break-words font-mono text-sm">{settings.model}</p></div><div><p className="eyebrow">API key</p><p className="mt-2 font-mono text-sm" translate="no">{settings.masked_key}</p></div></div><div className="mt-8 flex flex-wrap gap-2"><button className="button-primary" onClick={onTest} disabled={testPending}><KeyRound size={16} aria-hidden="true"/>{testPending?'Testing…':'Test Connection'}</button><button className="button-secondary" onClick={onEdit}>Update</button>{confirmRemove?<><button className="button-ghost text-danger" onClick={onRemove} disabled={removePending}><Trash2 size={16} aria-hidden="true"/>{removePending?'Removing…':'Confirm Remove'}</button><button className="button-ghost" onClick={onCancelRemove}>Keep</button></>:<button className="button-ghost text-danger" onClick={onConfirmRemove}><Trash2 size={16} aria-hidden="true"/>Remove</button>}</div>{testResult&&<p className={`mt-5 flex items-start gap-2 text-sm ${testResult.success?'text-success':'text-danger'}`} role="status" aria-live="polite">{testResult.success?<Check size={16} className="mt-0.5 shrink-0" aria-hidden="true"/>:<X size={16} className="mt-0.5 shrink-0" aria-hidden="true"/>}{testResult.success?'Connection works.':testResult.error||'The provider rejected the connection.'}</p>}</section>}

function SettingsForm({supported,current,pending,error,onCancel,onSave}:{supported:SupportedModels;current?:LLMSettings;pending:boolean;error?:string;onCancel?:()=>void;onSave:(value:{provider:string;model:string;api_key:string})=>void}){
  const curated=Object.keys(supported),curatedCurrent=!!current&&supported[current.provider]?.includes(current.model),initialProvider=current&&curatedCurrent?current.provider:curated[0]??'',[providerChoice,setProviderChoice]=useState(current&&!curatedCurrent?'custom':initialProvider||'custom'),[customProvider,setCustomProvider]=useState(current&&!curatedCurrent?current.provider:''),[model,setModel]=useState(current?.model??supported[initialProvider]?.[0]??''),[apiKey,setApiKey]=useState('')
  const custom=providerChoice==='custom',provider=custom?customProvider:providerChoice,models=supported[providerChoice]??[]
  return <form className="max-w-3xl border-y py-7" onSubmit={event=>{event.preventDefault();onSave({provider:provider.trim(),model:model.trim(),api_key:apiKey})}}><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold" htmlFor="provider">Provider<select id="provider" name="provider" className="field mt-2" value={providerChoice} onChange={event=>{const value=event.target.value;setProviderChoice(value);setModel(value==='custom'?'':supported[value]?.[0]??'')}}>{curated.map(item=><option value={item} key={item}>{item[0].toUpperCase()+item.slice(1)}</option>)}<option value="custom">Custom</option></select></label>{custom?<label className="text-sm font-semibold" htmlFor="custom-provider">Provider Name<input id="custom-provider" name="custom-provider" className="field mt-2" required autoComplete="off" value={customProvider} onChange={e=>setCustomProvider(e.target.value)} placeholder="mistral…"/></label>:<label className="text-sm font-semibold" htmlFor="model">Model<select id="model" name="model" className="field mt-2" value={model} onChange={e=>setModel(e.target.value)}>{models.map(item=><option value={item} key={item}>{item}</option>)}</select></label>}{custom&&<label className="text-sm font-semibold sm:col-start-2" htmlFor="custom-model">Model String<input id="custom-model" name="custom-model" className="field mt-2" required autoComplete="off" value={model} onChange={e=>setModel(e.target.value)} placeholder="mistral-large-latest…"/></label>}<label className="text-sm font-semibold sm:col-span-2" htmlFor="api-key">API Key<input id="api-key" name="api-key" className="field mt-2 font-mono" type="password" required autoComplete="new-password" spellCheck={false} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={current?'Enter a new key to update…':'Paste your provider API key…'}/></label></div>{error&&<p className="mt-4 text-sm text-danger" role="alert">{error}</p>}<div className="mt-7 flex flex-wrap justify-end gap-2">{onCancel&&<button type="button" className="button-ghost" onClick={onCancel}>Cancel</button>}<button className="button-primary" disabled={pending||!provider.trim()||!model.trim()||!apiKey}><Save size={16} aria-hidden="true"/>{pending?'Saving…':'Save API Key'}</button></div></form>
}
