import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronDown, ChevronUp, Pencil, Plus, Save, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { ScreenState } from '../components/ScreenState'
import { useApi } from '../hooks/useApi'
import type { BulletPoint, BulletPointInput, ItemType, SkillBankItem, SkillBankItemInput } from '../lib/types'

const labels:Record<ItemType,string>={experience:'Experience',project:'Projects',skill:'Skills',education:'Education',certification:'Certifications'}
const types=Object.keys(labels) as ItemType[]
const date=new Intl.DateTimeFormat(undefined,{year:'numeric',month:'short'})
const formatDate=(value:string|null)=>value?date.format(new Date(`${value}T00:00:00`)):'Present'

export function SkillBank(){
  const api=useApi(),queryClient=useQueryClient(),[params,setParams]=useSearchParams(),[expanded,setExpanded]=useState<string|null>(null),[editing,setEditing]=useState<SkillBankItem|'new'|null>(null)
  const requestedType=params.get('type'),tab=types.includes(requestedType as ItemType)?requestedType as ItemType:'experience'
  const items=useQuery({queryKey:['skill-bank'],queryFn:()=>api.skillBank.list()})
  const create=useMutation({mutationFn:api.skillBank.create,onSuccess:async item=>{await queryClient.invalidateQueries({queryKey:['skill-bank']});setEditing(null);setExpanded(item.id)}})
  const update=useMutation({mutationFn:({id,value}:{id:string;value:SkillBankItemInput})=>api.skillBank.update(id,value),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:['skill-bank']});setEditing(null)}})
  if(items.isPending)return <div className="px-5 py-8 md:px-10 xl:px-16"><ScreenState kind="loading" title="Loading your skill bank…" detail="Gathering your saved evidence."/></div>
  if(items.isError)return <div className="px-5 py-8 md:px-10 xl:px-16"><ScreenState kind="error" title="Skill bank unavailable" detail={items.error.message} onRetry={()=>void items.refetch()}/></div>
  const visible=items.data.filter(item=>item.type===tab)
  return <div className="page-enter px-5 py-8 md:px-10 md:py-12 xl:px-16"><PageHeader eyebrow="Evidence library" title="Skill Bank" description="Store the facts once. Tag each proof point so matching stays precise." action={<button className="button-primary" onClick={()=>setEditing('new')}><Plus size={16} aria-hidden="true"/>Add {labels[tab].toLowerCase()}</button>}/>
    <div role="tablist" aria-label="Skill bank sections" className="mb-8 flex gap-1 overflow-x-auto border-b">{types.map(type=><button key={type} role="tab" aria-selected={tab===type} onClick={()=>{setParams({type});setExpanded(null)}} className={`min-h-11 shrink-0 border-b-2 px-4 text-sm font-semibold transition-colors ${tab===type?'border-accent text-ink':'border-transparent text-muted hover:text-ink'}`}>{labels[type]} <span className="ml-1.5 font-mono text-xs tabular-nums">{items.data.filter(item=>item.type===type).length}</span></button>)}</div>
    {editing&&<ItemForm initial={editing==='new'?undefined:editing} type={tab} pending={create.isPending||update.isPending} error={(create.error??update.error)?.message} onClose={()=>setEditing(null)} onSave={value=>editing==='new'?create.mutate(value):update.mutate({id:editing.id,value})}/>}
    {!visible.length?<div className="grid min-h-72 place-items-center border-y text-center"><div><p className="font-display text-3xl">No {labels[tab].toLowerCase()} yet.</p><p className="mt-2 text-muted">Add the source material that future resumes can draw from.</p><button className="button-primary mt-5" onClick={()=>setEditing('new')}><Plus size={16} aria-hidden="true"/>Create First Entry</button></div></div>:<div className="divide-y border-y">{visible.map(item=><ItemRow key={item.id} item={item} open={expanded===item.id} onToggle={()=>setExpanded(expanded===item.id?null:item.id)} onEdit={()=>setEditing(item)}/>)}</div>}
  </div>
}

function ItemRow({item,open,onToggle,onEdit}:{item:SkillBankItem;open:boolean;onToggle:()=>void;onEdit:()=>void}){
  const api=useApi(),queryClient=useQueryClient(),[confirmDelete,setConfirmDelete]=useState(false)
  const detail=useQuery({queryKey:['skill-bank',item.id],queryFn:()=>api.skillBank.get(item.id),enabled:open})
  const remove=useMutation({mutationFn:()=>api.skillBank.delete(item.id),onSuccess:async()=>queryClient.invalidateQueries({queryKey:['skill-bank']})})
  return <article><button className="grid min-h-24 w-full grid-cols-[1fr_auto] items-center gap-4 py-5 text-left" aria-expanded={open} onClick={onToggle}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="section-title break-words">{item.title}</h2>{!item.end_date&&<span className="tag !border-success/30 !text-success">Current</span>}</div><p className="mt-1 text-sm text-muted">{item.org||'Independent'}{item.start_date?` · ${formatDate(item.start_date)}—${formatDate(item.end_date)}`:''}</p></div><ChevronDown aria-hidden="true" className={`text-muted transition-transform ${open?'rotate-180':''}`}/></button>{open&&<div className="pb-8 lg:pl-8">{detail.isPending?<div className="h-28 animate-pulse bg-surface"/>:detail.isError?<ScreenState kind="error" title="Entry unavailable" detail={detail.error.message} onRetry={()=>void detail.refetch()}/>:<><p className="mb-5 max-w-2xl whitespace-pre-wrap text-sm text-muted">{detail.data.raw_text||'No supporting notes yet.'}</p><BulletList itemId={item.id} bullets={[...detail.data.bullet_points].sort((a,b)=>a.display_order-b.display_order)}/><div className="mt-7 flex flex-wrap gap-2"><button className="button-secondary" onClick={onEdit}><Pencil size={15} aria-hidden="true"/>Edit Entry</button>{confirmDelete?<><button className="button-ghost text-danger" onClick={()=>remove.mutate()} disabled={remove.isPending}><Trash2 size={15} aria-hidden="true"/>{remove.isPending?'Deleting…':'Confirm Delete'}</button><button className="button-ghost" onClick={()=>setConfirmDelete(false)}>Keep Entry</button></>:<button className="button-ghost text-danger" onClick={()=>setConfirmDelete(true)}><Trash2 size={15} aria-hidden="true"/>Delete Entry</button>}</div>{remove.error&&<p className="mt-3 text-sm text-danger" role="alert">{remove.error.message}</p>}</>}</div>}</article>
}

function ItemForm({initial,type,pending,error,onClose,onSave}:{initial?:SkillBankItem;type:ItemType;pending:boolean;error?:string;onClose:()=>void;onSave:(value:SkillBankItemInput)=>void}){
  const [itemType,setItemType]=useState(initial?.type??type),[title,setTitle]=useState(initial?.title??''),[org,setOrg]=useState(initial?.org??''),[startDate,setStartDate]=useState(initial?.start_date??''),[endDate,setEndDate]=useState(initial?.end_date??''),[ongoing,setOngoing]=useState(!initial?.end_date),[rawText,setRawText]=useState(initial?.raw_text??'')
  return <form className="mb-8 border-y bg-surface py-6" onSubmit={event=>{event.preventDefault();onSave({type:itemType,title:title.trim(),org:org.trim()||null,start_date:startDate||null,end_date:ongoing?null:endDate||null,raw_text:rawText.trim()||null,tags:initial?.tags??[]})}}><div className="mb-5 flex items-center justify-between"><h2 className="section-title">{initial?'Edit':'New'} Entry</h2><button type="button" className="button-ghost" onClick={onClose} aria-label="Close form"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold" htmlFor="item-type">Type<select id="item-type" name="type" className="field mt-2" value={itemType} onChange={e=>setItemType(e.target.value as ItemType)}>{types.map(value=><option value={value} key={value}>{labels[value]}</option>)}</select></label><label className="text-sm font-semibold" htmlFor="item-title">Title<input id="item-title" name="title" className="field mt-2" value={title} required autoComplete="off" onChange={e=>setTitle(e.target.value)} placeholder="Product Engineer…"/></label><label className="text-sm font-semibold sm:col-span-2" htmlFor="item-org">Organization<input id="item-org" name="organization" className="field mt-2" value={org} autoComplete="organization" onChange={e=>setOrg(e.target.value)} placeholder="Company or institution…"/></label><label className="text-sm font-semibold" htmlFor="start-date">Start Date<input id="start-date" name="start-date" type="date" className="field mt-2" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label className="text-sm font-semibold" htmlFor="end-date">End Date<input id="end-date" name="end-date" type="date" className="field mt-2" value={endDate} disabled={ongoing} onChange={e=>setEndDate(e.target.value)}/></label><label className="flex min-h-11 items-center gap-3 text-sm font-semibold sm:col-span-2"><input type="checkbox" name="ongoing" checked={ongoing} onChange={e=>setOngoing(e.target.checked)}/>Ongoing / present</label><label className="text-sm font-semibold sm:col-span-2" htmlFor="raw-text">Source Notes<textarea id="raw-text" name="raw-text" className="field mt-2 min-h-32 resize-y py-3" value={rawText} onChange={e=>setRawText(e.target.value)} placeholder="Scope, context, and facts worth preserving…"/></label></div>{error&&<p className="mt-4 text-sm text-danger" role="alert">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" className="button-ghost" onClick={onClose}>Cancel</button><button className="button-primary" disabled={pending||!title.trim()}><Save size={16} aria-hidden="true"/>{pending?'Saving…':'Save Entry'}</button></div></form>
}

function BulletList({itemId,bullets}:{itemId:string;bullets:BulletPoint[]}){
  const api=useApi(),queryClient=useQueryClient(),[editing,setEditing]=useState<BulletPoint|'new'|null>(null),[confirmDelete,setConfirmDelete]=useState<string|null>(null)
  const refresh=()=>queryClient.invalidateQueries({queryKey:['skill-bank',itemId]})
  const create=useMutation({mutationFn:(value:BulletPointInput)=>api.skillBank.createBullet(itemId,{...value,display_order:Math.max(-1,...bullets.map(bullet=>bullet.display_order))+1}),onSuccess:async()=>{await refresh();setEditing(null)}})
  const update=useMutation({mutationFn:({id,value}:{id:string;value:BulletPointInput})=>api.skillBank.updateBullet(id,value),onSuccess:async()=>{await refresh();setEditing(null)}})
  const remove=useMutation({mutationFn:api.skillBank.deleteBullet,onSuccess:async()=>{await refresh();setConfirmDelete(null)}})
  const reorder=useMutation({mutationFn:async({bullet,index,direction}:{bullet:BulletPoint;index:number;direction:-1|1})=>{const other=bullets[index+direction];await Promise.all([api.skillBank.updateBullet(bullet.id,{display_order:other.display_order}),api.skillBank.updateBullet(other.id,{display_order:bullet.display_order})])},onSuccess:refresh})
  return <div><div className="mb-4 flex items-center justify-between"><p className="eyebrow">Proof Points</p><button className="button-secondary" onClick={()=>setEditing('new')}><Plus size={15} aria-hidden="true"/>Add Proof Point</button></div>{editing&&<BulletForm initial={editing==='new'?undefined:editing} pending={create.isPending||update.isPending} error={(create.error??update.error)?.message} onClose={()=>setEditing(null)} onSave={value=>editing==='new'?create.mutate(value):update.mutate({id:editing.id,value})}/>}<ol className="space-y-4">{bullets.map((bullet,index)=><li className="grid gap-3 border-l pl-4 sm:grid-cols-[1fr_auto]" key={bullet.id}><div className="min-w-0"><p className="text-sm leading-6"><span className="mr-2 font-mono text-xs text-muted">{String(index+1).padStart(2,'0')}</span>{bullet.text}</p><div className="mt-2 flex flex-wrap gap-1.5">{bullet.tags.map(tag=><span className="tag break-all" key={tag}>{tag}</span>)}</div></div><div className="flex items-start"><button className="button-ghost !px-2" aria-label={`Move proof point ${index+1} up`} disabled={index===0||reorder.isPending} onClick={()=>reorder.mutate({bullet,index,direction:-1})}><ChevronUp size={15}/></button><button className="button-ghost !px-2" aria-label={`Move proof point ${index+1} down`} disabled={index===bullets.length-1||reorder.isPending} onClick={()=>reorder.mutate({bullet,index,direction:1})}><ChevronDown size={15}/></button><button className="button-ghost !px-2" aria-label={`Edit proof point ${index+1}`} onClick={()=>setEditing(bullet)}><Pencil size={15}/></button>{confirmDelete===bullet.id?<button className="button-ghost !px-2 text-danger" aria-label={`Confirm delete proof point ${index+1}`} onClick={()=>remove.mutate(bullet.id)}><Trash2 size={15}/></button>:<button className="button-ghost !px-2" aria-label={`Delete proof point ${index+1}`} onClick={()=>setConfirmDelete(bullet.id)}><Trash2 size={15}/></button>}</div></li>)}{!bullets.length?<li className="border-l pl-4 text-sm text-muted">No proof points yet.</li>:null}</ol>{confirmDelete&&<p className="mt-3 text-xs text-muted">Click the red trash button again to confirm deletion.</p>}</div>
}

function BulletForm({initial,pending,error,onClose,onSave}:{initial?:BulletPoint;pending:boolean;error?:string;onClose:()=>void;onSave:(value:BulletPointInput)=>void}){const [text,setText]=useState(initial?.text??''),[tags,setTags]=useState(initial?.tags.join(', ')??''),[metrics,setMetrics]=useState(initial?.metrics??'');return <form className="mb-5 bg-raised p-4" onSubmit={event=>{event.preventDefault();onSave({text:text.trim(),tags:tags.split(',').map(tag=>tag.trim()).filter(Boolean),metrics:metrics.trim()||null,display_order:initial?.display_order})}}><label className="text-sm font-semibold" htmlFor="bullet-text">Proof Point<textarea id="bullet-text" name="bullet-text" className="field mt-2 min-h-24 resize-y py-3" required autoComplete="off" value={text} onChange={e=>setText(e.target.value)} placeholder="Describe the action and outcome…"/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold" htmlFor="bullet-tags">Tags<input id="bullet-tags" name="bullet-tags" className="field mt-2" autoComplete="off" value={tags} onChange={e=>setTags(e.target.value)} placeholder="React, TypeScript…"/><span className="mt-1 block text-xs font-normal text-muted">Separate tags with commas.</span></label><label className="text-sm font-semibold" htmlFor="bullet-metrics">Metric<input id="bullet-metrics" name="bullet-metrics" className="field mt-2" autoComplete="off" value={metrics} onChange={e=>setMetrics(e.target.value)} placeholder="31% reduction…"/></label></div>{error&&<p className="mt-3 text-sm text-danger" role="alert">{error}</p>}<div className="mt-4 flex justify-end gap-2"><button type="button" className="button-ghost" onClick={onClose}>Cancel</button><button className="button-primary" disabled={pending||!text.trim()}><Save size={15} aria-hidden="true"/>{pending?'Saving…':'Save Proof Point'}</button></div></form>}
