import { ChevronDown, Plus, Save, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { skillBank as initial } from '../lib/demo'
import type { ItemType, SkillBankItem } from '../lib/types'
const labels:Record<ItemType,string>={experience:'Experience',project:'Projects',skill:'Skills',education:'Education'}
export function SkillBank(){const [items,setItems]=useState(initial);const [tab,setTab]=useState<ItemType>('experience');const [expanded,setExpanded]=useState<string|null>('exp-1');const [editing,setEditing]=useState(false);const visible=items.filter(i=>i.type===tab);const deleteItem=(id:string)=>setItems(x=>x.filter(i=>i.id!==id));return <div className="page-enter px-5 py-8 md:px-10 md:py-12 xl:px-16"><PageHeader eyebrow="Evidence library" title="Skill bank" description="Store the facts once. Tag each proof point so matching stays precise." action={<button className="button-primary" onClick={()=>setEditing(true)}><Plus size={16}/>Add {labels[tab].toLowerCase()}</button>}/>
  <div role="tablist" aria-label="Skill bank sections" className="mb-8 flex gap-1 overflow-x-auto border-b">{(Object.keys(labels) as ItemType[]).map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} className={`min-h-11 shrink-0 border-b-2 px-4 text-sm font-semibold transition ${tab===t?'border-accent text-ink':'border-transparent text-muted hover:text-ink'}`}>{labels[t]} <span className="ml-1.5 font-mono text-xs">{items.filter(i=>i.type===t).length}</span></button>)}</div>
  {editing&&<InlineForm type={tab} onClose={()=>setEditing(false)} onSave={item=>{setItems(x=>[item,...x]);setEditing(false);setExpanded(item.id)}}/>}
  {visible.length===0?<div className="grid min-h-72 place-items-center border-y text-center"><div><p className="font-display text-3xl">No {labels[tab].toLowerCase()} yet.</p><p className="mt-2 text-muted">Add the source material that future resumes can draw from.</p><button className="button-primary mt-5" onClick={()=>setEditing(true)}><Plus size={16}/>Create first entry</button></div></div>:<div className="divide-y border-y">{visible.map(item=>{const open=expanded===item.id;return <article key={item.id}><button className="grid min-h-24 w-full grid-cols-[1fr_auto] items-center gap-4 py-5 text-left" aria-expanded={open} onClick={()=>setExpanded(open?null:item.id)}><div><div className="flex flex-wrap items-center gap-2"><h2 className="section-title">{item.title}</h2>{item.endDate==='Present'&&<span className="tag !border-success/30 !text-success">Current</span>}</div><p className="mt-1 text-sm text-muted">{item.organization}{item.location&&` · ${item.location}`} {item.startDate&&` · ${item.startDate}—${item.endDate}`}</p></div><ChevronDown className={`text-muted transition-transform ${open?'rotate-180':''}`}/></button><div className={`grid transition-[grid-template-rows] duration-300 ${open?'grid-rows-[1fr]':'grid-rows-[0fr]'}`}><div className="overflow-hidden"><div className="pb-8 lg:pl-8"><p className="mb-5 max-w-2xl text-sm text-muted">{item.description}</p><ol className="space-y-3">{item.bullets.map((b,index)=><li className="grid gap-3 border-l pl-4 sm:grid-cols-[1fr_auto]" key={b.id}><div><p className="text-sm leading-6"><span className="mr-2 font-mono text-xs text-muted">{String(index+1).padStart(2,'0')}</span>{b.text}</p><div className="mt-2 flex flex-wrap gap-1.5">{b.tags.map(t=><span className="tag" key={t.id}>{t.name}</span>)}</div></div><button className="button-ghost self-start" aria-label={`Delete bullet ${index+1}`}><Trash2 size={15}/></button></li>)}</ol><div className="mt-6 flex gap-2"><button className="button-secondary"><Plus size={15}/>Add proof point</button><button className="button-ghost text-danger" onClick={()=>deleteItem(item.id)}><Trash2 size={15}/>Delete entry</button></div></div></div></div></article>})}</div>}
  </div>}
function InlineForm({type,onClose,onSave}:{type:ItemType;onClose:()=>void;onSave:(item:SkillBankItem)=>void}){const [title,setTitle]=useState('');const [org,setOrg]=useState('');return <form className="mb-8 border-y bg-surface py-6" onSubmit={e=>{e.preventDefault();onSave({id:crypto.randomUUID(),type,title,organization:org,bullets:[],skills:[]})}}><div className="mb-5 flex items-center justify-between"><h2 className="section-title">New {labels[type].toLowerCase()}</h2><button type="button" className="button-ghost" onClick={onClose} aria-label="Close form"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Title<input className="field mt-2" value={title} required onChange={e=>setTitle(e.target.value)} placeholder={type==='education'?'B.Tech, Computer Science':'Product Engineer'}/></label><label className="text-sm font-semibold">Organization<input className="field mt-2" value={org} onChange={e=>setOrg(e.target.value)} placeholder="Company or institution"/></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" className="button-ghost" onClick={onClose}>Keep browsing</button><button className="button-primary"><Save size={16}/>Save entry</button></div></form>}
