\documentclass[10pt]{article}
\usepackage[margin=0.65in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\pagenumbering{gobble}
\setlength{\parindent}{0pt}
\setlist[itemize]{leftmargin=*,nosep}
\begin{document}
$header
$sections
\end{document}
