import { useQuery } from '@tanstack/react-query'
import { BookOpen, FileInput, LayoutDashboard, LogOut, Menu, Moon, Settings, Sun, X } from 'lucide-react'
import { Link, NavLink, Outlet } from 'react-router-dom'
import { Logo } from './Logo'
import { useUI } from '../store/ui'
import { ApiError } from '../lib/api'
import { useApi } from '../hooks/useApi'
import { useAuth } from '../hooks/useAuth'
const nav=[['/dashboard','Dashboard',LayoutDashboard],['/skill-bank','Skill bank',BookOpen],['/job-description','Job descriptions',FileInput],['/settings','Settings',Settings]] as const
export function AppShell(){const {theme,toggleTheme,mobileNav,setMobileNav}=useUI();const {user,signOut}=useAuth();const api=useApi();const {data:llmSettings,error:llmError}=useQuery({queryKey:['llm-settings'],queryFn:api.llmSettings.get,retry:(count,error)=>error instanceof ApiError&&error.status===404?false:count<1});const missing=!llmSettings&&llmError instanceof ApiError&&llmError.status===404;const name=user?.user_metadata.full_name??user?.user_metadata.name??user?.user_metadata.user_name??'Your workspace';const email=user?.email??'Personal workspace';return <div className="min-h-screen lg:grid lg:grid-cols-[16rem_1fr]">
  <a className="skip-link" href="#main-content">Skip to main content</a>
  <header className="no-print sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-canvas/95 px-4 backdrop-blur lg:hidden"><Logo/><button className="button-ghost" aria-label={mobileNav?'Close navigation':'Open navigation'} onClick={()=>setMobileNav(!mobileNav)}>{mobileNav?<X aria-hidden="true"/>:<Menu aria-hidden="true"/>}</button></header>
  <aside className={`no-print fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r bg-canvas px-4 pb-5 pt-6 transition-transform duration-300 lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${mobileNav?'translate-x-0':'-translate-x-full'}`}>
    <div className="mb-10 px-2"><Logo/></div><nav className="flex-1" aria-label="Primary"><ul className="space-y-1">{nav.map(([to,label,Icon])=><li key={to}><NavLink to={to} onClick={()=>setMobileNav(false)} className={({isActive})=>`flex min-h-11 items-center gap-3 rounded-lg px-3 text-sm font-medium transition-colors ${isActive?'bg-ink text-canvas':'text-muted hover:bg-surface hover:text-ink'}`}><Icon size={17} aria-hidden="true"/>{label}</NavLink></li>)}</ul></nav>
    <div className="border-t pt-4"><button className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm text-muted hover:bg-surface hover:text-ink" onClick={toggleTheme}>{theme==='light'?<Moon size={17} aria-hidden="true"/>:<Sun size={17} aria-hidden="true"/>} {theme==='light'?'Dark':'Light'} appearance</button><div className="mt-3 flex items-center gap-3 px-3"><div className="grid size-8 shrink-0 place-items-center rounded-full bg-accent-soft text-xs font-bold text-accent" aria-hidden="true">{String(name).slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{String(name)}</p><p className="truncate text-xs text-muted">{email}</p></div><button className="text-muted hover:text-ink" aria-label="Sign out" title="Sign out" onClick={()=>void signOut()}><LogOut size={17} aria-hidden="true"/></button></div></div>
  </aside>{mobileNav&&<button className="fixed inset-0 z-30 bg-ink/30 lg:hidden" aria-label="Close navigation" onClick={()=>setMobileNav(false)}/>}<main id="main-content" className="min-w-0">{missing&&<div className="no-print flex flex-wrap items-center justify-between gap-3 border-b border-accent/25 bg-accent-soft px-5 py-3 text-sm" role="status"><p><strong>AI provider needed.</strong> Add your own provider key before parsing job descriptions.</p><Link className="font-semibold text-accent underline underline-offset-4" to="/settings">Open Settings</Link></div>}<Outlet/></main>
</div>}
